// Generates lib/src/features/emoji/data/unicode_emoji_data.dart from the
// unicode_emojis dev dependency, keeping only what the emoji picker needs so
// the app doesn't ship the package's 2 MB dataset.
//
// Run from the project root: dart run tool/generate_unicode_emojis.dart

import 'dart:convert';
import 'dart:io';

import 'package:unicode_emojis/unicode_emojis.dart' as ue;
import 'package:youtube_takeout_manager/src/features/emoji/domain/unicode_emoji.dart';

const _output = 'lib/src/features/emoji/data/unicode_emoji_data.dart';
final _plainName = RegExp(r'^[\w-]+$');

/// Where Discord and iOS file emojis differently from Unicode: Symbols opens
/// with the hearts and marks (💯 💢 💬 💤) Unicode lists under Smileys &
/// Emotion (the kiss mark stays with People), and Nature ends with the sky
/// and weather (☀️ 🌙 ⭐ 🔥 🌊) Unicode lists under Travel & Places.
UnicodeEmojiCategory? _discordCategory(ue.Emoji emoji) =>
    switch (emoji.subcategory) {
      'heart' => UnicodeEmojiCategory.symbols,
      'emotion' when emoji.shortName != 'kiss' => UnicodeEmojiCategory.symbols,
      'sky & weather' => UnicodeEmojiCategory.nature,
      _ => null,
    };

UnicodeEmojiCategory _categoryOf(ue.Emoji emoji) =>
    _discordCategory(emoji) ?? _unicodeCategory(emoji.category);

UnicodeEmojiCategory _unicodeCategory(ue.Category category) =>
    switch (category) {
      ue.Category.smileysAndEmotion ||
      ue.Category.peopleAndBody => UnicodeEmojiCategory.people,
      ue.Category.animalsAndNature => UnicodeEmojiCategory.nature,
      ue.Category.foodAndDrink => UnicodeEmojiCategory.food,
      ue.Category.activities => UnicodeEmojiCategory.activities,
      ue.Category.travelAndPlaces => UnicodeEmojiCategory.travel,
      ue.Category.objects => UnicodeEmojiCategory.objects,
      ue.Category.symbols => UnicodeEmojiCategory.symbols,
      ue.Category.flags => UnicodeEmojiCategory.flags,
    };

String _packageVersion() {
  final lock = File('pubspec.lock').readAsStringSync();
  final match = RegExp(
    r'\n  unicode_emojis:\n(?:    .*\n)*?    version: "([^"]+)"',
  ).firstMatch(lock);
  return match?[1] ?? 'unknown';
}

void _checkField(String value) {
  if (value.contains('\t') || value.contains('\n')) {
    throw FormatException('Field contains a tab or newline', value);
  }
}

Future<void> main() async {
  final emojis = [...ue.UnicodeEmojis.allEmojis]
    ..sort((a, b) => a.sortOrder.compareTo(b.sortOrder));

  final rows = {for (final c in UnicodeEmojiCategory.values) c: <String>[]};
  final usedNames = <String>{};
  for (final emoji in emojis) {
    // The skin tone swatches (🏻…🏿) aren't emojis anyone picks.
    if (emoji.shortName.startsWith('skin-tone-')) continue;

    final names = <String>[];
    for (final raw in emoji.shortNames) {
      final name = raw.toLowerCase();
      if (!_plainName.hasMatch(name)) continue;
      if (!usedNames.add(name)) {
        stdout.writeln('Duplicate name :$name: on ${emoji.emoji}, dropped');
        continue;
      }
      names.add(name);
    }
    if (names.isEmpty) {
      stdout.writeln('Skipped ${emoji.emoji} (${emoji.name}): no usable name');
      continue;
    }

    _checkField(emoji.emoji);
    _checkField(emoji.name);
    rows[_categoryOf(emoji)]!.add(
      '${emoji.emoji}\t${names.join(' ')}\t${emoji.name}',
    );
  }

  String literal(String row) => jsonEncode(row).replaceAll(r'$', r'\$');

  final out = StringBuffer()
    ..writeln(
      '// GENERATED by tool/generate_unicode_emojis.dart from '
      'unicode_emojis ${_packageVersion()}.',
    )
    ..writeln('// Do not edit by hand; re-run the tool instead.')
    ..writeln('//')
    ..writeln(
      '// Row: emoji \\t short names (space-separated, first is primary) '
      '\\t Unicode name.',
    )
    ..writeln()
    ..writeln("import '../domain/unicode_emoji.dart';")
    ..writeln()
    ..writeln('const unicodeEmojiRows = <UnicodeEmojiCategory, List<String>>{');
  for (final MapEntry(key: category, value: list) in rows.entries) {
    out.writeln('  UnicodeEmojiCategory.${category.name}: [');
    for (final row in list) {
      out.writeln('    ${literal(row)},');
    }
    out.writeln('  ],');
  }
  out.writeln('};');

  File(_output).writeAsStringSync(out.toString());
  final format = await Process.run('dart', [
    'format',
    _output,
  ], runInShell: true);
  if (format.exitCode != 0) {
    stderr.write(format.stderr);
    exitCode = format.exitCode;
    return;
  }

  final total = rows.values.fold(0, (sum, list) => sum + list.length);
  stdout.writeln('Wrote $total emojis to $_output');
  for (final MapEntry(key: category, value: list) in rows.entries) {
    stdout.writeln('  ${category.label}: ${list.length}');
  }
}
